### ISSUE TITLE
Headphones after sleep

### ISSUE THREAD

**Issue by jief666** [hackintosh-stuff/ComboJack#12]
Hi,
I have a dell XPS 9560.

I put my computer to sleep with headphones plugged in, after wake I have no sound. If I start ComboJack by hand and select Headphones in the popup, sound is back.

My question is : is the windows asking for Line-in, Headset or Headphones is supposed to appear at wake ?

Thanks for that dev.

**Comment by maz-1** [comment]
Yes, it should appear at wake.

**Comment by jief666** [comment]
Ok thanks.
At first I thought it never does on my computer. But I have to say that I'm pretty sure after I wrote that issue that I saw it at wake.
I also have issue with the computer waking up in the middle of the night.
My speakers died and was replaced by USB ones.
Long story short : I can't really tell.
Sorry for disturbance.
