### ISSUE TITLE
Did not work on Big Sur beta 9 OC 6.2 ALC256

### ISSUE THREAD

**Issue by diepeterpan** [hackintosh-stuff/ComboJack#21]
I did not work for me on Big Sur beta 9 OC 6.2 ALC256; the responsecode were 8 bytes, unsigned long and the first six byte were all high. Hack a code fixed it -   **responsecode = (responsecode << 40) >> 40;**

   while(true)
    {	    {
        //wait until user logged in	        //wait until user logged in
@@ -660,7 +662,11 @@ uint32_t CFPopUpMenu()
     kCFUserNotificationOtherResponse       = 2,	     kCFUserNotificationOtherResponse       = 2,
     kCFUserNotificationCancelResponse      = 3	     kCFUserNotificationCancelResponse      = 3
     */	     */

    fprintf(stderr, "Response code after: %lu.\n", responsecode);
    **responsecode = (responsecode << 40) >> 40;**
    fprintf(stderr, "Response code fixed: %lu.\n", responsecode);

    switch (responsecode)	    switch (responsecode)

**Comment by Andrw0830** [comment]
Hey man! I have the same issue with ComboJack not working with Big Sur, just trying to figure out exactly what you changed to fix the issue? I've found the response section in the hda-verb.m file, but can't find out where to put the "responsecode = (responsecode << 40) >> 40;" line you've said. Or if it's easier, do you have the ComboJack file compiled that you don't mind sharing?

Thanks, appreciate the help!

**Comment by diepeterpan** [comment]
> Hey man! I have the same issue with ComboJack not working with Big Sur, just trying to figure out exactly what you changed to fix the issue? I've found the response section in the hda-verb.m file, but can't find out where to put the "responsecode = (responsecode << 40) >> 40;" line you've said. Or if it's easier, do you have the ComboJack file compiled that you don't mind sharing?
> 
> Thanks, appreciate the help!

Look here -> https://github.com/diepeterpan/Acer-Swift-3-SF314-54-2018-MacOS-Big-Sur/commit/60b224be212fae1bd4e75bdcf795559ef17deb3d

**Comment by Andrw0830** [comment]
> > Hey man! I have the same issue with ComboJack not working with Big Sur, just trying to figure out exactly what you changed to fix the issue? I've found the response section in the hda-verb.m file, but can't find out where to put the "responsecode = (responsecode << 40) >> 40;" line you've said. Or if it's easier, do you have the ComboJack file compiled that you don't mind sharing?
> > Thanks, appreciate the help!
> 
> Look here -> [diepeterpan/Acer-Swift-3-SF314-54-2018-MacOS-Big-Sur@60b224b](https://github.com/diepeterpan/Acer-Swift-3-SF314-54-2018-MacOS-Big-Sur/commit/60b224be212fae1bd4e75bdcf795559ef17deb3d)

Thanks man! Much appreciated! It works great!

**Comment by maz-1** [comment]
> > Hey man! I have the same issue with ComboJack not working with Big Sur, just trying to figure out exactly what you changed to fix the issue? I've found the response section in the hda-verb.m file, but can't find out where to put the "responsecode = (responsecode << 40) >> 40;" line you've said. Or if it's easier, do you have the ComboJack file compiled that you don't mind sharing?
> > Thanks, appreciate the help!
> 
> Look here -> [diepeterpan/Acer-Swift-3-SF314-54-2018-MacOS-Big-Sur@60b224b](https://github.com/diepeterpan/Acer-Swift-3-SF314-54-2018-MacOS-Big-Sur/commit/60b224be212fae1bd4e75bdcf795559ef17deb3d)

Good work, a pull request maybe?

**Comment by diepeterpan** [comment]
> > > Hey man! I have the same issue with ComboJack not working with Big Sur, just trying to figure out exactly what you changed to fix the issue? I've found the response section in the hda-verb.m file, but can't find out where to put the "responsecode = (responsecode << 40) >> 40;" line you've said. Or if it's easier, do you have the ComboJack file compiled that you don't mind sharing?
> > > Thanks, appreciate the help!
> > 
> > 
> > Look here -> [diepeterpan/Acer-Swift-3-SF314-54-2018-MacOS-Big-Sur@60b224b](https://github.com/diepeterpan/Acer-Swift-3-SF314-54-2018-MacOS-Big-Sur/commit/60b224be212fae1bd4e75bdcf795559ef17deb3d)
> 
> Good work, a pull request maybe?

Apology; not 100% familiar with GitHub.

**Comment by diepeterpan** [comment]
> > > > Hey man! I have the same issue with ComboJack not working with Big Sur, just trying to figure out exactly what you changed to fix the issue? I've found the response section in the hda-verb.m file, but can't find out where to put the "responsecode = (responsecode << 40) >> 40;" line you've said. Or if it's easier, do you have the ComboJack file compiled that you don't mind sharing?
> > > > Thanks, appreciate the help!
> > > 
> > > 
> > > Look here -> [diepeterpan/Acer-Swift-3-SF314-54-2018-MacOS-Big-Sur@60b224b](https://github.com/diepeterpan/Acer-Swift-3-SF314-54-2018-MacOS-Big-Sur/commit/60b224be212fae1bd4e75bdcf795559ef17deb3d)
> > 
> > 
> > Good work, a pull request maybe?
> 
> Apology; not 100% familiar with GitHub.

Ok, pull request created.

**Comment by Hoangpham89** [comment]
this is miner malwave so be careful.

**Comment by maz-1** [comment]
> this is miner malwave so be careful.

I don't accept accuse without proof. This is open source tool, you can always inspect the code.

**Comment by Hoangpham89** [comment]
> > this is miner malwave so be careful.
> 
> I don't accept accuse without proof. This is open source tool, you can always inspect the code.

I am sorry, I've just had problem with Cleanmymac application. It work well.

**Comment by diepeterpan** [comment]
Fixed
