### ISSUE TITLE
Flagged as malware in CleanMyMac

### ISSUE THREAD

**Issue by jonaolden** [hackintosh-stuff/ComboJack#28]
This keeps getting flagged as coin miner in CleanMyMac. Is there any substance in this? 
![image](https://user-images.githubusercontent.com/20564977/106188716-990b0100-61a7-11eb-9224-35ad9f88faa9.png)

**Comment by maz-1** [comment]
Does it cause high cpu usage?

**Comment by uttusharma** [comment]
I believe it is a false positive
