### ISSUE TITLE
睡眠后拔掉耳机，唤醒后还是有选择耳麦弹框

### ISSUE THREAD

**Issue by hoanX** [hackintosh-stuff/ComboJack#3]
hi，
提个小问题：插着耳机进入睡眠，睡眠后拔掉耳机，唤醒后还是弹选择耳麦的弹框
小建议：选择耳麦选项能不能放到系统设置里面，或者状态栏插件，这样不用每次都选择

**Comment by maz-1** [comment]
你可以按escape取消
放到系统设置或者状态栏要另外写gui组件，我懒得去熟悉objc那套东西

**Comment by maz-1** [comment]
问题重现不了。睡眠时拔掉耳机唤醒后不会弹出对话框。
