### ISSUE TITLE
CleanMyMac alert Coinminer after run install.sh on Big Sur 11.6.1

### ISSUE THREAD

**Issue by oldman20** [hackintosh-stuff/ComboJack#34]
![Screen Shot 2021-11-07 at 17 25 24](https://user-images.githubusercontent.com/39668756/140641243-941a861c-c7e0-428a-b151-e0e6835e9c67.png)
Anyone have same? is it safe?

**Comment by maz-1** [comment]
Compile by yourself.

**Comment by oldman20** [comment]
> Compile by yourself.

oh thank for suggest!

**Comment by oldman20** [comment]
how can i compile it by myself, sorry im amateur!

**Comment by maz-1** [comment]
Then use pre-compiled binaried and forget false alarms from cleanmymac shit
